plugin: aws_ec2

aws_access_key: AKIA5SAX4KHKUMPOROGR
aws_secret_key: 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

regions:
  - us-east-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
